FROM node:15 as build

WORKDIR ./app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .


ENTRYPOINT ["npm", "start"]

RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=build /app/build /user/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]