FROM node:14-bullseye as build

WORKDIR ./app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000
# npm run nodemon --watch server
ENTRYPOINT ["npm", "start"]
# FROM nginx:stable-alpine
# EXPOSE 80
# COPY --from=build /app/build /usr/share/nginx/html

# CMD ["npm", "start"]