version: "3"

networks:
  nodeapp-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
     - nodeapp-network
    ports:
      - "80:80"
