version: "3"

networks:
  nodeapp-network:
    driver: bridge

services:
  app:
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
     - nodeapp-network
    ports:
      - "80:80"
