version: "3"

networks:
  nodeapp-network:
    driver: bridge

services:
  app:
    env_file:
     - .env
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
     - nodeapp-network
    ports:
      - "5001:5001"
