version: "3"

# networks:
#   nodeapp-network:
#     driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # networks:
    #  - nodeapp-network
    ports:
      - "80:3004"
    volumes:
      - ./client/src:/app/src
