version: "3"

networks:
  nodeapp-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
     - nodeapp-network
    ports:
      - "3000:3000"
