FROM node:14-bullseye as build

WORKDIR ./app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3004
# npm run nodemon --watch server
# ENTRYPOINT ["npm", "start"]
# FROM nginx:stable-alpine
# EXPOSE 80
# COPY --from=build /app/build /usr/share/nginx/html

RUN npm run build-prod

FROM nginx
COPY --from=build /app/build /user/share/nginx/html